- hosts: deb1
  vars:
    domains:
     - domain1.locAl
     - DomaIn2.global
    allowgroups: 
     - superGroup
  #become: true
  #become_user: root

  tasks:

   - template:
      src: /home/ansible/Ansible/drafts/templates/sssd.conf.j2
      dest: /home/ansible/Ansible/drafts/sssd.conf.result
#    owner: bin
#    group: wheel
#    mode: 0644
