- hosts: deb2
  become: true
  tasks:
    - name: Install prereqs
      apt: pkg={{item}} state=present update_cache=yes
      with_items: ["git", "build-essential", "libcurl4-gnutls-dev", "postgresql-server-dev-{{postgresql_version}}"]
 
    - name: Git clone postgre http-extension
      git:
       repo: "https://github.com/pramsey/pgsql-http"
       dest: "/usr/local/src/pgsql-http"
       update: no
      register: pghttpdown

    - name: Postgresql http-extension compiling
      command: "make install"
      args:
       chdir: "/usr/local/src/pgsql-http/"
      when: pghttpdown.changed

    - name: Postgresql http-extension installation
      postgresql_ext:
       name: http
       db: queues
      when: pghttpdown.changed
 
    - name: Set proper owner to http extension 
      command: psql queues -c "UPDATE pg_extension SET extowner=(select usesysid from pg_user where usename = '{{queuesuser}}') where extname = 'http';"
      become_user: postgres
      when: pghttpdown.changed


#  roles:
#    - role: ANXS.postgresql
  vars:
      queuesuser: uouser
      postgresql_version: 9.6
      postgresql_locale: 'ru_RU.UTF-8'
      postgresql_ctype: 'ru_RU.UTF-8'
      postgresql_ext_install_contrib: yes
      postgresql_ext_install_dev_headers: yes
      postgresql_databases:
       - name: 'queues'
         owner: '{{queuesuser}}'
       - name: 'smp'
         owner: '{{queuesuser}}'
       - name: 'web_patients'
         owner: '{{queuesuser}}'
 
      postgresql_users: 
       - name: '{{queuesuser}}'
         pass: benQ1234	
         encrypted: yes
        # role_attr_flags: "SUPERUSER"
      

#      postgresql_user_privileges:
#       - name: uouser                # user name
#         db: queues                  # database
#         priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
#       - name: uouser                # user name
#         db: smp                     # database
#         priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
#       - name: uouser                # user name
#         db: web_patients            # database
#         priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL

      postgresql_pg_hba_passwd_hosts:
        - '10.0.0.0/8'
        - '192.168.0.0/16'
      postgresql_listen_addresses: ['*']
      postgresql_max_connections: 100
      postgresql_shared_buffers: "{{(ansible_memtotal_mb * 0.2)|int}}MB"
      postgresql_effective_cache_size: "{{(ansible_memtotal_mb * 0.75)|int}}MB"
      postgresql_work_mem: "{{(ansible_memtotal_mb * 0.02)|int}}MB"
      postgresql_maintenance_work_mem: "{{(ansible_memtotal_mb * 0.064)|int}}MB" 
      postgresql_min_wal_size: 1GB
      postgresql_max_wal_size: 2GB
      postgresql_checkpoint_completion_target: 0.7
      postgresql_default_statistics_target: 500
#      postgresql_pgtune: yes
      # Total system memory in bytes, will attempt to detect if set to "no"
#      postgresql_pgtune_memory: no
      # Database type, valid options are DW, OLTP, Web, Mixed, Desktop
#      postgresql_pgtune_type: Web
      # Maximum number of expected connections, if "no", default based on db type
#      postgresql_pgtune_connections: "{{postgresql_max_connections}}"
      postgresql_log_checkpoints: on 
      postgresql_log_line_prefix: '%m %p %u@%d from %h [vxid:%v txid:%x] [%i] ' 
      postgresql_lc_messages: 'en_US.UTF-8'
      postgresql_vacuum_cost_delay: 10
      postgresql_vacuum_cost_page_hit: 1
      postgresql_vacuum_cost_page_miss: 1
      postgresql_vacuum_cost_page_dirty: 10
      postgresql_vacuum_cost_limit: 1000
      postgresql_log_min_duration_statement: 3000
